# Request
float32 meters
float32 meters_per_second
---
# Result
geometry_msgs/Point final_position
geometry_msgs/Point goal_position
---
# Feedback
geometry_msgs/Point current_position
geometry_msgs/Point goal_position
